# Generated by Django 5.0.7 on 2024-09-21 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20240921_1210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='desc',
        ),
    ]
