# Generated by Django 5.0.7 on 2024-09-21 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_order_desc'),
    ]

    operations = [
    ]
