# Generated by Django 5.0.7 on 2024-09-21 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_order_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='order',
            name='phone_number',
            field=models.CharField(default=0, max_length=20),
        ),
    ]
