# Generated by Django 5.0.7 on 2024-09-21 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_order_address_order_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_number', models.CharField(max_length=255, unique=True)),
                ('issued_to', models.CharField(max_length=255)),
            ],
        ),
    ]
